spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':   # this matches all paths
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true



