# Deployment for Prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-prometheus
  template:
    metadata:
      labels:
        app: ecom-prometheus
    spec:
      containers:
      - name: ecom-prometheus
        image: prom/prometheus:latest
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml

volumes:
- name: prometheus-config
  configMap:
    name: prometheus-config

---

# Service for Prometheus
apiVersion: v1
kind: Service
metadata:
  name: ecom-prometheus
spec:
  selector:
    app: ecom-prometheus
  ports:
  - protocol: TCP
    port: 3198
    targetPort: 9090
