---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-microservice-timescale-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # You should adjust this size based on your needs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-master-db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-master-db-service
  template:
    metadata:
      labels:
        app: ecom-master-db-service
    spec:
      containers:
      - name: ecom-master-db-container
        image: timescale/timescaledb:latest-pg15
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: janny
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: ecommerce-microservice-timescale-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: ecommerce-microservice-timescale-data
        persistentVolumeClaim:
          claimName: ecommerce-microservice-timescale-data

---
apiVersion: v1
kind: Service
metadata:
  name: ecom-master-db-service
spec:
  selector:
    app: ecom-master-db-service
  ports:
  - protocol: TCP
    port: 3155
    targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  POSTGRES_PASSWORD: QWoxODk2MjhA  # This is "Aj189628@" base64 encoded. Remember to update if the password changes!
