spring:
  application:
    name: ecom-api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':   # this matches all paths
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
logging:
  level:
    org.springframework.web.cors: DEBUG
server:
  port: 3099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3145/eureka/  # Eureka server location

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints, be cautious with this in production
  tracing:
    sampling:
      probability: 1.0