spring:
  application:
    name: ecom-api-gateway
  cloud:
    gateway:
      routes:
      - id: auth-service-route
        uri: lb://ECOM-AUTH-SERVICE/
        predicates:
        - Path=/api/auth-service/**
      - id: master-service-route
        uri: lb://ECOM-MASTER-SERVICE/
        predicates:
        - Path=/api/master-service/**
      - id: profile-service-route
        uri: lb://ECOM-PROFILE-SERVICE/
        predicates:
        - Path=/api/profile-service/**
      - id: file-service-route
        uri: lb://ECOM-FILE-SERVICE/
        predicates:
        - Path=/api/file-service/**
      - id: catalog-service-route
        uri: lb://ECOM-CATALOGUE-SERVICE/
        predicates:
        - Path=/api/catalog-service/**
      - id: recom-service-route
        uri: lb://ECOM-RECOM-SERVICE/
        predicates:
        - Path=/api/recom-service/**
  config:
    import: "optional:configserver:http://localhost:3088"

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.boot.actuate: DEBUG
server:
  port: 3099
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3145/eureka/  # Eureka server location 