spring:
  application:
    name: ecom-api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"


server:
  port: 3099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:3145/eureka/  # Eureka server location

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all actuator endpoints, be cautious with this in production
  tracing:
    sampling:
      probability: 1.0