spring:
  application:
    name: ecom-api-gateway
  cloud:
    gateway:
      routes:
      - id: auth-service-route
        uri: lb://ECOM-AUTH-SERVICE/
        predicates:
        - Path=/api/auth-service/**
      - id: master-service-route
        uri: lb://ECOM-MASTER-SERVICE/
        predicates:
        - Path=/api/master-service/**
      - id: profile-service-route
        uri: lb://ECOM-PROFILE-SERVICE/
        predicates:
        - Path=/api/profile-service/**
      - id: file-service-route
        uri: lb://ECOM-FILE-SERVICE/
        predicates:
        - Path=/api/file-service/**
      - id: catalogue-service-route
        uri: lb://ECOM-CATALOGUE-SERVICE/
        predicates:
        - Path=/api/catalogue-service/**
      - id: recom-service-route
        uri: lb://ECOM-RECOM-SERVICE/
        predicates:
        - Path=/api/recom-service/**
  config:
    import: "optional:configserver:http://192.168.30.28:3088"

logging:
  level:
    org.springframework.web.cors: DEBUG
    org.springframework.boot.actuate: DEBUG
server:
  port: 3099
  host: 192.168.30.28
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.30.28:3192/api/v2/spans
eureka:
  client:
    service-url:
      defaultZone: http://192.168.30.28:3145/eureka/  # Eureka server location 